In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("logiccraftbyhimanshi/walmart-customer-purchase-behavior-dataset")

print("Path to dataset files:", path)

Path to dataset files: /Users/santiagonovoa/.cache/kagglehub/datasets/logiccraftbyhimanshi/walmart-customer-purchase-behavior-dataset/versions/1

In [14]:
import kagglehub
import os
import pandas as pd

# Download dataset
path = kagglehub.dataset_download(
    "frtgnn/dunnhumby-the-complete-journey"
)

print("Dataset folder:", path)

# See what files are actually there
print(os.listdir(path))

Dataset folder: /Users/santiagonovoa/.cache/kagglehub/datasets/frtgnn/dunnhumby-the-complete-journey/versions/1
['hh_demographic.csv', 'causal_data.csv', 'coupon.csv', 'campaign_table.csv', 'coupon_redempt.csv', 'product.csv', 'campaign_desc.csv', 'transaction_data.csv']

In [26]:
transactions = pd.read_csv(
    os.path.join(path, "transaction_data.csv")
)


print(transactions.shape)

(2595732, 12)

In [27]:
transactions

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,0.0,0.0
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,0.0,0.0
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,0.0,0.0
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,0.0,0.0
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2595727,1598,42305362535,711,92130,1,0.99,3228,0.00,1520,102,0.0,0.0
2595728,1598,42305362535,711,114102,1,8.89,3228,0.00,1520,102,0.0,0.0
2595729,1598,42305362535,711,133449,1,6.99,3228,0.00,1520,102,0.0,0.0
2595730,1598,42305362535,711,6923644,1,4.50,3228,-0.49,1520,102,0.0,0.0
2595731,1598,42305362535,711,14055192,1,6.99,3228,0.00,1520,102,0.0,0.0

In [24]:
print("Households:", transactions["household_key"].nunique())

Households: 2500

In [29]:
print("Baskets:", transactions["BASKET_ID"].nunique())

Baskets: 276484

In [32]:
print("Products:", transactions["PRODUCT_ID"].nunique())

Products: 92339

In [35]:
print(
    transactions[["DAY", "WEEK_NO"]]
    .agg(["min", "max"])
)

     DAY  WEEK_NO
min    1        1
max  711      102

In [38]:
print(products["PRODUCT_ID"].duplicated().sum())

0

In [39]:
print(demographics["household_key"].duplicated().sum())

0

In [17]:
products = pd.read_csv(
    os.path.join(path, "product.csv")
)
print(products.shape)

(92353, 7)

In [20]:
demographics = pd.read_csv(
    os.path.join(path, "hh_demographic.csv")
)

print(demographics.shape)

(801, 8)

In [21]:
demographics

,AGE_DESC,MARITAL_STATUS_CODE,INCOME_DESC,HOMEOWNER_DESC,HH_COMP_DESC,HOUSEHOLD_SIZE_DESC,KID_CATEGORY_DESC,household_key
0,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1
1,45-54,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7
2,25-34,U,25-34K,Unknown,2 Adults Kids,3,1,8
3,25-34,U,75-99K,Homeowner,2 Adults Kids,4,2,13
4,45-54,B,50-74K,Homeowner,Single Female,1,None/Unknown,16
...,...,...,...,...,...,...,...,...
796,35-44,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,2494
797,45-54,A,75-99K,Homeowner,Unknown,3,1,2496
798,45-54,U,35-49K,Unknown,Single Male,1,None/Unknown,2497
799,25-34,U,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,2498
800,25-34,U,Under 15K,Unknown,2 Adults Kids,3,1,2499

In [ ]:
df = (
    transactions
    .merge(
        products,
        on="PRODUCT_ID",
        how="left",
        validate="m:1"
    )
    .merge(
        demographics,
        on="household_key",
        how="left",
        validate="m:1" 
    )
)

In [41]:
df

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,TRANS_TIME,WEEK_NO,...,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT,AGE_DESC,MARITAL_STATUS_CODE,INCOME_DESC,HOMEOWNER_DESC,HH_COMP_DESC,HOUSEHOLD_SIZE_DESC,KID_CATEGORY_DESC
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,...,POTATOES,POTATOES RUSSET (BULK&BAG),5 LB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,...,ONIONS,ONIONS SWEET (BULK&BAG),40 LB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,...,VEGETABLES - ALL OTHERS,CELERY,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,...,TROPICAL FRUIT,BANANAS,40 LB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,...,ORGANICS FRUIT & VEGETABLES,ORGANIC CARROTS,1 LB,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2595727,1598,42305362535,711,92130,1,0.99,3228,0.00,1520,102,...,MARGARINES,MARGARINE: TUBS AND BOWLS,16 OZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2595728,1598,42305362535,711,114102,1,8.89,3228,0.00,1520,102,...,BEERS/ALES,BEERALEMALT LIQUORS,12 OZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2595729,1598,42305362535,711,133449,1,6.99,3228,0.00,1520,102,...,BEERS/ALES,BEERALEMALT LIQUORS,12 OZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2595730,1598,42305362535,711,6923644,1,4.50,3228,-0.49,1520,102,...,BEERS/ALES,BEERALEMALT LIQUORS,4PK/10 OZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2595731,1598,42305362535,711,14055192,1,6.99,3228,0.00,1520,102,...,MISC WINE,BEERALEMALT LIQUORS,6PK/11.2OZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
past = df[df["WEEK_NO"] <= 52].copy()
future = df[df["WEEK_NO"] > 52].copy()

In [45]:
print("Overall weeks:", df["WEEK_NO"].min(), "to", df["WEEK_NO"].max())

print("\nPAST")
print("Weeks:", past["WEEK_NO"].min(), "to", past["WEEK_NO"].max())
print("Households:", past["household_key"].nunique())
print("Baskets:", past["BASKET_ID"].nunique())

print("\nFUTURE")
print("Weeks:", future["WEEK_NO"].min(), "to", future["WEEK_NO"].max())
print("Households:", future["household_key"].nunique())
print("Baskets:", future["BASKET_ID"].nunique())

Overall weeks: 1 to 102

PAST
Weeks: 1 to 52
Households: 2497
Baskets: 127956

FUTURE
Weeks: 53 to 102
Households: 2479
Baskets: 148528

In [46]:
past_households = set(past["household_key"])
future_households = set(future["household_key"])

print("In both:", len(past_households & future_households))
print("Past only:", len(past_households - future_households))
print("Future only:", len(future_households - past_households))

In both: 2476
Past only: 21
Future only: 3

In [47]:
past_behavior = (
    past.groupby("household_key")
    .agg(
        trips=("BASKET_ID", "nunique"),
        spend=("SALES_VALUE", "sum"),
        active_weeks=("WEEK_NO", "nunique"),
        commodity_breadth=("COMMODITY_DESC", "nunique"),
        product_breadth=("PRODUCT_ID", "nunique")
    )
    .reset_index()
)

In [48]:
past_behavior["trips_per_active_week"] = (
    past_behavior["trips"] / past_behavior["active_weeks"]
)

past_behavior["spend_per_trip"] = (
    past_behavior["spend"] / past_behavior["trips"]
)

In [49]:
future_value = (
    future.groupby("household_key")
    .agg(
        future_trips=("BASKET_ID", "nunique"),
        future_spend=("SALES_VALUE", "sum"),
        future_active_weeks=("WEEK_NO", "nunique")
    )
    .reset_index()
)

In [50]:
analysis = past_behavior.merge(
    future_value,
    on="household_key",
    how="left",
    validate="1:1"
)

analysis[
    ["future_trips", "future_spend", "future_active_weeks"]
] = analysis[
    ["future_trips", "future_spend", "future_active_weeks"]
].fillna(0)

In [51]:
analysis.describe().T

,count,mean,std,min,25%,50%,75%,max
household_key,2497.0,1249.643572,721.765411,1.0,625.000000,1249.000000,1874.000000,2500.000000
trips,2497.0,51.243893,57.484713,1.0,16.000000,35.000000,66.000000,629.000000
spend,2497.0,1447.013276,1564.236717,1.0,399.920000,948.600000,1944.740000,13137.440000
active_weeks,2497.0,22.889868,12.650801,1.0,12.000000,23.000000,33.000000,52.000000
commodity_breadth,2497.0,85.154586,43.160360,1.0,51.000000,85.000000,117.000000,226.000000
product_breadth,2497.0,297.918302,253.914966,1.0,107.000000,234.000000,418.000000,2196.000000
trips_per_active_week,2497.0,1.920460,1.223154,1.0,1.250000,1.566667,2.073171,17.472222
spend_per_trip,2497.0,31.182776,20.324221,1.0,17.334286,26.801071,39.508125,187.280000
future_trips,2497.0,59.468963,65.045749,0.0,19.000000,41.000000,78.000000,686.000000
future_spend,2497.0,1779.285691,1947.152024,0.0,452.910000,1161.010000,2445.110000,25559.790000
future_active_weeks,2497.0,26.749700,14.678971,0.0,14.000000,27.000000,40.000000,50.000000

In [52]:
analysis["high_value"] = (
    analysis["future_trips"] >= 78
).astype(int)

In [54]:
analysis["high_value"].value_counts()

high_value
0    1859
1     638
Name: count, dtype: int64

In [55]:
analysis["high_value"].mean()

np.float64(0.2555066079295154)

In [56]:
analysis["breadth_quartile"] = pd.qcut(
    analysis["commodity_breadth"],
    4,
    labels=["Q1", "Q2", "Q3", "Q4"]
)

breadth_summary = (
    analysis.groupby("breadth_quartile", observed=True)
    .agg(
        households=("household_key", "count"),
        avg_past_trips=("trips", "mean"),
        avg_future_trips=("future_trips", "mean"),
        avg_future_spend=("future_spend", "mean"),
        high_value_rate=("high_value", "mean")
    )
)

breadth_summary

,households,avg_past_trips,avg_future_trips,avg_future_spend,high_value_rate
breadth_quartile,,,,,
Q1,625,14.539200,24.116800,500.433024,0.035200
Q2,627,32.639553,42.031898,1048.120797,0.141946
Q3,635,53.664567,61.683465,1751.519496,0.261417
Q4,610,105.454098,111.308197,3870.031328,0.591803

In [57]:
analysis[
    [
        "trips",
        "spend",
        "active_weeks",
        "commodity_breadth",
        "product_breadth",
        "future_trips"
    ]
].corr().round(2)

,trips,spend,active_weeks,commodity_breadth,product_breadth,future_trips
trips,1.00,0.70,0.72,0.64,0.70,0.78
spend,0.70,1.00,0.71,0.82,0.91,0.58
active_weeks,0.72,0.71,1.00,0.79,0.74,0.58
commodity_breadth,0.64,0.82,0.79,1.00,0.91,0.53
product_breadth,0.70,0.91,0.74,0.91,1.00,0.57
future_trips,0.78,0.58,0.58,0.53,0.57,1.00

In [59]:
import statsmodels.formula.api as smf

model = smf.logit(
    "high_value ~ trips + commodity_breadth",
    data=analysis
).fit()

print(model.summary())

Optimization terminated successfully.
         Current function value: 0.357082
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:             high_value   No. Observations:                 2497
Model:                          Logit   Df Residuals:                     2494
Method:                           MLE   Df Model:                            2
Date:                Sun, 20 Sep 2026   Pseudo R-squ.:                  0.3717
Time:                        20:20:42   Log-Likelihood:                -891.63
converged:                       True   LL-Null:                       -1419.1
Covariance Type:            nonrobust   LLR p-value:                8.786e-230
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            -4.1154      0.190    -21.690      0.000      -4.487      -3.743
trips                 0.0351      0.002     15.755      0.000       0.031       0.039
commodity_breadth     0.0109      0.002      5.246      0.000       0.007       0.015
=====================================================================================

In [60]:
analysis["trips_10"] = analysis["trips"] / 10
analysis["commodity_breadth_10"] = analysis["commodity_breadth"] / 10

model = smf.logit(
    "high_value ~ trips_10 + commodity_breadth_10",
    data=analysis
).fit()

print(model.summary())

Optimization terminated successfully.
         Current function value: 0.357082
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:             high_value   No. Observations:                 2497
Model:                          Logit   Df Residuals:                     2494
Method:                           MLE   Df Model:                            2
Date:                Sun, 20 Sep 2026   Pseudo R-squ.:                  0.3717
Time:                        20:21:01   Log-Likelihood:                -891.63
converged:                       True   LL-Null:                       -1419.1
Covariance Type:            nonrobust   LLR p-value:                8.786e-230
========================================================================================
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept               -4.1154      0.190    -21.690      0.000      -4.487      -3.743
trips_10                 0.3505      0.022     15.755      0.000       0.307       0.394
commodity_breadth_10     0.1086      0.021      5.246      0.000       0.068       0.149
========================================================================================

In [61]:
import numpy as np

np.exp(model.params)

Intercept               0.016320
trips_10                1.419823
commodity_breadth_10    1.114696
dtype: float64

In [62]:
analysis["trip_quartile"] = pd.qcut(
    analysis["trips"],
    4,
    labels=["Q1", "Q2", "Q3", "Q4"]
)

In [63]:
analysis["high_breadth_within_trip_group"] = (
    analysis.groupby("trip_quartile", observed=True)["commodity_breadth"]
    .transform(lambda x: x >= x.median())
)

In [64]:
comparison = (
    analysis.groupby(
        ["trip_quartile", "high_breadth_within_trip_group"],
        observed=True
    )
    .agg(
        households=("household_key", "count"),
        avg_past_trips=("trips", "mean"),
        avg_commodity_breadth=("commodity_breadth", "mean"),
        avg_future_trips=("future_trips", "mean"),
        high_value_rate=("high_value", "mean")
    )
)

comparison

                                              households  avg_past_trips  \
trip_quartile high_breadth_within_trip_group
Q1            False                                  316        6.632911
              True                                   320       11.081250
Q2            False                                  313       23.971246
              True                                   322       26.881988
Q3            False                                  306       47.509804
              True                                   307       50.687296
Q4            False                                  304      102.542763
              True                                   309      145.252427

                                              avg_commodity_breadth  \
trip_quartile high_breadth_within_trip_group
Q1            False                                       18.971519
              True                                        58.906250
Q2            False                                       53.127796
              True                                        97.562112
Q3            False                                       76.676471
              True                                       123.407166
Q4            False                                      102.720395
              True                                       152.640777

                                              avg_future_trips  \
trip_quartile high_breadth_within_trip_group
Q1            False                                  16.493671
              True                                   19.996875
Q2            False                                  33.309904
              True                                   38.329193
Q3            False                                  57.392157
              True                                   62.586319
Q4            False                                 108.282895
              True                                  143.757282

                                              high_value_rate
trip_quartile high_breadth_within_trip_group
Q1            False                                  0.015823
              True                                   0.006250
Q2            False                                  0.060703
              True                                   0.074534
Q3            False                                  0.235294
              True                                   0.270358
Q4            False                                  0.611842
              True                                   0.799353

In [65]:
import numpy as np
import statsmodels.formula.api as smf

analysis["log_trips"] = np.log1p(analysis["trips"])
analysis["log_future_trips"] = np.log1p(analysis["future_trips"])
analysis["commodity_breadth_10"] = analysis["commodity_breadth"] / 10

model_trips = smf.ols(
    "log_future_trips ~ log_trips + commodity_breadth_10",
    data=analysis
).fit(cov_type="HC3")

print(model_trips.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       log_future_trips   R-squared:                       0.550
Model:                            OLS   Adj. R-squared:                  0.550
Method:                 Least Squares   F-statistic:                     1092.
Date:                Sun, 20 Sep 2026   Prob (F-statistic):               0.00
Time:                        20:32:53   Log-Likelihood:                -2760.4
No. Observations:                2497   AIC:                             5527.
Df Residuals:                    2494   BIC:                             5544.
Df Model:                           2
Covariance Type:                  HC3
========================================================================================
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                0.9174      0.074     12.321      0.000       0.771       1.063
log_trips                0.7079      0.029     24.261      0.000       0.651       0.765
commodity_breadth_10     0.0257      0.006      4.467      0.000       0.014       0.037
==============================================================================
Omnibus:                      280.587   Durbin-Watson:                   1.946
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              753.479
Skew:                          -0.618   Prob(JB):                    2.42e-164
Kurtosis:                       5.390   Cond. No.                         41.4
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

In [66]:
analysis["log_spend"] = np.log1p(analysis["spend"])

model_trips_2 = smf.ols(
    "log_future_trips ~ log_trips + log_spend + commodity_breadth_10",
    data=analysis
).fit(cov_type="HC3")

print(model_trips_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       log_future_trips   R-squared:                       0.550
Model:                            OLS   Adj. R-squared:                  0.550
Method:                 Least Squares   F-statistic:                     801.9
Date:                Sun, 20 Sep 2026   Prob (F-statistic):               0.00
Time:                        20:33:04   Log-Likelihood:                -2759.0
No. Observations:                2497   AIC:                             5526.
Df Residuals:                    2493   BIC:                             5549.
Df Model:                           3
Covariance Type:                  HC3
========================================================================================
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                1.1149      0.177      6.305      0.000       0.768       1.461
log_trips                0.7309      0.032     22.526      0.000       0.667       0.795
log_spend               -0.0546      0.041     -1.347      0.178      -0.134       0.025
commodity_breadth_10     0.0359      0.009      3.915      0.000       0.018       0.054
==============================================================================
Omnibus:                      285.635   Durbin-Watson:                   1.947
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              751.479
Skew:                          -0.635   Prob(JB):                    6.58e-164
Kurtosis:                       5.369   Cond. No.                         113.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)